use pizza_project;
select * from order_details;
select * from orders;
alter table orders modify date date;
alter table orders modify time time;
select * from pizza_types;
select * from pizzas;
-- -----------------------------------------------------------------------------------
-- Chapter 2
-- Task 1
select count(*) as total_orders_placed
from orders;

-- Task 2
with cal_rev as (
select od.* ,p.price
from order_details as od
left join
pizzas as p
on od.pizza_id = p.pizza_id)

select sum(quantity * price ) as Total_revenue
from cal_rev;

-- Task 3
select *
from pizzas
order by price desc
limit 1;

-- Task 4
with com_psize as (
select od.* ,p.size
from order_details as od
left join
pizzas as p
on od.pizza_id = p.pizza_id)
select size as common_psize,count(order_details_id) as total_count
from com_psize
group by size 
order by total_count desc
limit 1;
-- -------------------------------------------------------------------------------------------------------------------
-- Chapter 3 
-- Task 1
with ptype as (
select od.* ,p.pizza_type_id
from order_details as od
left join
pizzas as p
on od.pizza_id = p.pizza_id)

select pizza_type_id , sum(quantity) as total_quantity
from ptype 
group by pizza_type_id
order by total_quantity desc
limit 5;

-- Task 2

select hour(time) as hour_of_day, count(order_id) as total_count
from orders
group by hour(time)
order by hour_of_day;

-- Task 3

with ptype as (
select od.* ,p.pizza_type_id, p.price
from order_details as od
left join pizzas as p on od.pizza_id = p.pizza_id
)

select pizza_type_id, sum(price*quantity) as total_rev_for_ptype
from ptype
group by pizza_type_id
order by total_rev_for_ptype desc
limit 3;

-- --------------------------------------------------------------------------------------------------------

-- Chapter 4
-- Task 1

with cal_rev as (
select od.* ,p.price, p.pizza_type_id                                  -- Doing left join to bring in pizza price and pizz type id
from order_details as od
left join
pizzas as p
on od.pizza_id = p.pizza_id),

ptype_rev as(select pizza_type_id, sum(total_price) as type_totalp     -- Calculating revenue generated by each pizza type
from (select *, quantity*price as total_price from cal_rev) as tp      -- using cte cal_rev inside  cte ptype_rev
group by pizza_type_id),

per_contri as                                                           -- Doing cross join to add total revenue of all pizzas column
(select ptr.*, tr.*                                                     -- for making calculations easier further
from ptype_rev as ptr                                                   -- using cte ptype_rev inside cte per_contri
cross join 
(select sum(quantity * price ) as Total_revenue
from cal_rev) as tr )

select *, concat(type_totalp*100/Total_revenue,'%') as ptype_rev_contri  -- Finding contribution percentage of each pizza
from per_contri;                                                         -- type to tatal revenue


-- Task 2

with req_table as
( 	select o.order_id,o.date,od.order_details_id,od.pizza_id,od.quantity, p.price   -- Cumulative rev over date, so orders table is left table
	from orders as o
    left join order_details as od on o.order_id=od.order_id
    left join pizzas as p on od.pizza_id=p.pizza_id
)

select *, sum(price*quantity) over (partition by date) as per_day_rev
from req_table ;

-- Task 3

with req_table as(
select o.*, p.pizza_type_id, p.size, p.price, pt.name, pt.category
from order_details as o
left join pizzas as p on o.pizza_id=p.pizza_id
left join pizza_types as pt on p.pizza_type_id=pt.pizza_type_id),

gen_rev as
(select *, sum(price*quantity) 
over (partition by category,pizza_type_id ) as per_category_type_rev
from req_table
)

select distinct(per_category_type_rev),pizza_type_id, category, tp3.drank
from(select * ,dense_rank() over (partition by category order by per_category_type_rev desc) as drank
	from gen_rev) as tp3
where tp3.drank <=3;

-- -------------------------------------------------------------------------------------------------------

-- Chapter 5
-- Task 1

select pt.category, sum(quantity) as total_category_quantity        -- only while doing the join you want to see all columns 
from order_details as od                                            -- during group by you can remove those columns to aggreagate
left join pizzas as p on od.pizza_id=p.pizza_id
left join pizza_types as pt on p.pizza_type_id=pt.pizza_type_id
group by category;

-- Task 2

with catd as(
select pt.category, sum(quantity) as total_category_quantity       -- only while doing the join you want to see all columns 
from order_details as od                                            -- during group by you can remove those columns to aggreagate
left join pizzas as p on od.pizza_id=p.pizza_id
left join pizza_types as pt on p.pizza_type_id=pt.pizza_type_id
group by category)

select category, concat(total_category_quantity*100/(select sum(total_category_quantity) from catd),'%') as percetage_dist
from catd;                                                             -- used sub query

-- Task 3

with cal_avg as
(select o.date, sum(quantity) as total_pizza_pday
from order_details as od
left join orders as o on od.order_id=o.order_id
group by date)

select sum(total_pizza_pday)/count(date) as avg_pizz_per_day
from cal_avg;
-- ------------------------------------------------------------------------------------------------------



















